// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU0R_gxX279bKFWfDLQyMc7uEcCKzuloM',
    appId: '1:246091998684:web:bbe69989fb18e447c11b19',
    messagingSenderId: '246091998684',
    projectId: 'todolist-4e497',
    authDomain: 'todolist-4e497.firebaseapp.com',
    storageBucket: 'todolist-4e497.appspot.com',
    measurementId: 'G-5Z92LRS5VR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhupoKEPy35CeGVOg5fE435MORYTYubJs',
    appId: '1:246091998684:android:5476b6386055f389c11b19',
    messagingSenderId: '246091998684',
    projectId: 'todolist-4e497',
    storageBucket: 'todolist-4e497.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEZSUqr-DlOezvVyBhKmnRWQkwgw91Wzg',
    appId: '1:246091998684:ios:61596b7f66e2632ec11b19',
    messagingSenderId: '246091998684',
    projectId: 'todolist-4e497',
    storageBucket: 'todolist-4e497.appspot.com',
    iosClientId: '246091998684-lecggs65r0p56fbcsaq9ke3g2448pu77.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEZSUqr-DlOezvVyBhKmnRWQkwgw91Wzg',
    appId: '1:246091998684:ios:1f401af61d9b00cfc11b19',
    messagingSenderId: '246091998684',
    projectId: 'todolist-4e497',
    storageBucket: 'todolist-4e497.appspot.com',
    iosClientId: '246091998684-vgoui8i5bvc70uq27qr4qe6v6qvlac8e.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolistApp.RunnerTests',
  );
}
